import { IsString, IsEmail, IsNotEmpty, IsOptional, IsBoolean, IsDateString } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';

export class CreateTeacherDto {
    @ApiProperty({ example: 'John', description: 'First name of the teacher' })
    @IsString()
    @IsNotEmpty()
    firstName: string;

    @ApiProperty({ example: 'Doe', description: 'Last name of the teacher' })
    @IsString()
    @IsNotEmpty()
    lastName: string;

    @ApiProperty({ example: 'john.doe@school.com', description: 'Email of the teacher', required: false })
    @IsOptional()
    @IsEmail()
    email?: string;

    @ApiProperty({ example: true, description: 'Is the teacher active?', required: false })
    @IsOptional()
    @IsBoolean()
    isActive?: boolean;

    @ApiProperty({ example: '1234567890', description: 'Mobile number of the teacher', required: false })
    @IsOptional()
    @IsString()
    mobile?: string;

    @ApiProperty({ example: 'Female', description: 'Gender of the teacher', required: false })
    @IsOptional()
    @IsString()
    gender?: string;

    // --- Teacher-specific optional fields ---
    // employeeCode is auto-generated by the system on creation.

    @ApiProperty({ example: 'Science', description: 'Department the teacher belongs to', required: false })
    @IsOptional()
    @IsString()
    department?: string;

    @ApiProperty({ example: '2020-06-01', description: 'Date of joining the school (YYYY-MM-DD)', required: false })
    @IsOptional()
    @IsDateString()
    joiningDate?: string;

    @ApiProperty({ example: '2025-12-31', description: 'Exit date if teacher left the school (YYYY-MM-DD)', required: false })
    @IsOptional()
    @IsDateString()
    exitDate?: string;

    @ApiProperty({ example: 'M.Sc, B.Ed', description: 'Highest qualification of the teacher', required: false })
    @IsOptional()
    @IsString()
    qualification?: string;
}
